id: P009152
initial_creation_type: ocr
source_metadata:
  id: bdr:W2DB4629
  title: གཡུ་ཐོག་སྨན་ཡིག་ཕྱོགས་བསྒྲིགས
  author: ''
  volumes:
    b25cf0184930489b880aebf5b0a8cd8d:
      image_group_id: I1PD28100
      title: ''
      volume_number: 1
      total_pages: 368
