id: I40B7166A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T13:26:00+00:00'
last_modified: '2022-06-08T08:59:31.731878+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2DB4629
  title: གཡུ་ཐོག་སྨན་ཡིག་ཕྱོགས་བསྒྲིགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A36F:
      image_group_id: I1PD28100
      title: ''
      total_pages: 368
      order: 1
      base_file: A36F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
